version: '3.8'

services:
  etcd:
    image: gcr.io/etcd-development/etcd:v3.5.9
    container_name: etcd-single
    command: >
      /usr/local/bin/etcd 
      --name etcd-single 
      --initial-advertise-peer-urls http://0.0.0.0:2380 
      --listen-peer-urls http://0.0.0.0:2380 
      --advertise-client-urls http://0.0.0.0:2379 
      --listen-client-urls http://0.0.0.0:2379 
      --initial-cluster-token etcd-cluster-1 
      --initial-cluster etcd-single=http://0.0.0.0:2380 
      --initial-cluster-state new
    ports:
      - "2379:2379"
      - "2380:2380"
